//! Structural 3-way merge for Cargo.lock.
//!
//! Treats the lockfile as a set of package entries keyed by exact
//! `name@version` identity, 3-way merges the sets, then collapses
//! semver-compatible duplicates (introduced when both branches bumped the
//! same dependency to different versions) by keeping the highest. Cargo
//! normalizes the details on the next build; the point is that two branches
//! touching the lockfile stops being an automatic conflict.
//!
//! Invoked by the gitwasm host as: cargo-lock-merge <base> <ours> <theirs> <result> [path]

use std::collections::BTreeMap;
use std::process::exit;
use toml::{Table, Value};

fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.len() < 5 {
        eprintln!("usage: cargo-lock-merge <base> <ours> <theirs> <result> [path]");
        exit(2);
    }
    let base = read_lock(&args[1]);
    let ours = read_lock(&args[2]);
    let theirs = read_lock(&args[3]);

    // 3-way merge of the entry sets.
    let mut keys: Vec<&String> = base
        .keys()
        .chain(ours.keys())
        .chain(theirs.keys())
        .collect();
    keys.sort();
    keys.dedup();
    let mut merged: BTreeMap<String, Table> = BTreeMap::new();
    for key in keys {
        let (b, o, t) = (base.get(key), ours.get(key), theirs.get(key));
        let winner = if o == t {
            o
        } else if o == b {
            t
        } else if t == b {
            o
        } else {
            // Same name@version, differing metadata on both sides (checksum or
            // dependency edits). Extremely rare; take theirs and say so rather
            // than block — cargo will validate the checksum on next build.
            eprintln!("cargo-lock-merge: {key}: metadata differs on both sides, taking theirs");
            t
        };
        if let Some(entry) = winner {
            merged.insert(key.clone(), entry.clone());
        }
    }

    // Collapse semver-compatible duplicates: keep the highest version.
    let mut by_bucket: BTreeMap<(String, String), (Vec<u64>, String, Table)> = BTreeMap::new();
    for (key, entry) in merged {
        let (name, version) = split_key(&key);
        let parsed = parse_version(version);
        let bucket = (name.to_string(), compat_bucket(&parsed));
        match by_bucket.get(&bucket) {
            Some((existing, existing_ver, _)) if *existing >= parsed => {
                eprintln!(
                    "cargo-lock-merge: {name}: both branches bumped, keeping {existing_ver} over {version}"
                );
            }
            Some((_, dropped, _)) => {
                eprintln!(
                    "cargo-lock-merge: {name}: both branches bumped, keeping {version} over {dropped}"
                );
                by_bucket.insert(bucket, (parsed, version.to_string(), entry));
            }
            None => {
                by_bucket.insert(bucket, (parsed, version.to_string(), entry));
            }
        }
    }

    let packages: Vec<Value> = by_bucket
        .into_values()
        .map(|(_, _, e)| Value::Table(e))
        .collect();
    let mut doc = Table::new();
    doc.insert("version".into(), Value::Integer(4));
    doc.insert("package".into(), Value::Array(packages));

    let body = toml::to_string(&doc).expect("serialize merged Cargo.lock");
    let text = format!(
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\n{body}"
    );
    std::fs::write(&args[4], text).expect("write result");
    eprintln!("cargo-lock-merge: clean structural merge");
}

/// Parse a Cargo.lock into entries keyed by `name@version`.
fn read_lock(path: &str) -> BTreeMap<String, Table> {
    let text = std::fs::read_to_string(path).unwrap_or_default();
    if text.trim().is_empty() {
        return BTreeMap::new();
    }
    let doc: Table = match text.parse() {
        Ok(doc) => doc,
        Err(err) => {
            eprintln!("cargo-lock-merge: {path} is not valid TOML ({err}) — refusing");
            exit(1);
        }
    };
    let mut entries = BTreeMap::new();
    if let Some(Value::Array(packages)) = doc.get("package") {
        for pkg in packages {
            if let Value::Table(table) = pkg {
                let name = table.get("name").and_then(Value::as_str).unwrap_or("");
                let version = table.get("version").and_then(Value::as_str).unwrap_or("");
                entries.insert(format!("{name}@{version}"), table.clone());
            }
        }
    }
    entries
}

fn split_key(key: &str) -> (&str, &str) {
    key.rsplit_once('@').unwrap_or((key, ""))
}

/// Numeric version components; pre-release/build metadata is dropped for
/// comparison (a released version always beats its own pre-releases here,
/// which is the right bias for a lockfile).
fn parse_version(version: &str) -> Vec<u64> {
    version
        .split(['-', '+'])
        .next()
        .unwrap_or("")
        .split('.')
        .map(|part| part.parse().unwrap_or(0))
        .collect()
}

/// Cargo semver compatibility: same major, or same minor when major is 0.
fn compat_bucket(parsed: &[u64]) -> String {
    match parsed {
        [0, minor, ..] => format!("0.{minor}"),
        [major, ..] => major.to_string(),
        [] => String::new(),
    }
}
